#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""すごろくを、マス番号と効果が対応する整列済みテキスト盤面へ更新する。"""

from pathlib import Path

path = Path('ERB/EVENT_BOARD_イベントボード周回.ERB')
text = path.read_bytes().decode('cp932').replace('\r\n', '\n')

draw_start = text.index('@SUGOROKU_DRAW_BOARD')
draw_end = text.index('\n@SUGOROKU_PRINT_CELL', draw_start)
cell_start = draw_end + 1
cell_end = text.index(';---------------------------------------------------------\n; アイテム使用', cell_start)

draw = r'''@SUGOROKU_DRAW_BOARD
; 盤面アートはresources配下を確認してから、Emueraのspriteとして表示する。
LOCALS:1 '= @"sugoroku_board_festival.png"
LOCALS:4 '= @"resources/%LOCALS:1%"
IF EXISTFILE(LOCALS:4)
	SPRITEDISPOSE "sugoroku_board"
	GDISPOSE 0
	GCREATEFROMFILE 0, LOCALS:1
	IF GCREATED(0)
		GDISPOSE 1
		GCREATEFROMFILE 1, "sugoroku_pawn_token.png"
		CALL SUGOROKU_DRAW_PAWN, FLAG:33
		SPRITECREATE "sugoroku_board", 0, 0, 0, GWIDTH(0), GHEIGHT(0)
		LOCALS:3 '= @"<img src='sugoroku_board' height='320px'>"
		HTML_PRINT LOCALS:3, 1
		REPEAT 20
			PRINTL
		REND
	ENDIF
ENDIF
DRAWLINE
SETCOLOR 0xFFCC66
PRINTFORML 【すごろく　周回:{FLAG:37}　現在地:{FLAG:33}/19】
RESETCOLOR
; 外周を時計回りに進む：上段0～8、右中央9、下段10～18、左中央19。
SETCOLOR 0xAAAAAA
PRINTFORM 　　　
RESETCOLOR
FOR LOCAL:8, 0, 9
	CALL SUGOROKU_PRINT_CELL, LOCAL:8
NEXT
PRINTL
SETCOLOR 0xAAAAAA
PRINTFORM 　　　
RESETCOLOR
CALL SUGOROKU_PRINT_CELL, 19
REPEAT 7
	PRINTFORM 　　　
REND
CALL SUGOROKU_PRINT_CELL, 9
PRINTL
SETCOLOR 0xAAAAAA
PRINTFORM 　　　
RESETCOLOR
FOR LOCAL:8, 0, 9
	LOCAL:9 = 18 - LOCAL:8
	CALL SUGOROKU_PRINT_CELL, LOCAL:9
NEXT
PRINTL
SETCOLOR 0x888888
PRINTFORML ──────────────────────────────────────────────────────────────
RESETCOLOR
; 色とマス効果を一対一に対応させた凡例
SETCOLOR 0x00FF80
PRINTFORM [発]
RESETCOLOR
PRINTFORM 開始・周回　
SETCOLOR 0x88CCFF
PRINTFORM [通]
RESETCOLOR
PRINTFORM 通常　
SETCOLOR 0xFF8800
PRINTFORM [特]
RESETCOLOR
PRINTFORM 特大　
SETCOLOR 0xFF2200
PRINTFORM [緊]
RESETCOLOR
PRINTFORM 緊急　
SETCOLOR 0xFFCC00
PRINTFORM [★]
RESETCOLOR
PRINTFORM ボーナス　
SETCOLOR 0x88FF44
PRINTFORM [品]
RESETCOLOR
PRINTFORML アイテム
SETCOLOR 0x44AAFF
PRINTFORM [休]
RESETCOLOR
PRINTFORM 休憩　
SETCOLOR 0xCC7722
PRINTFORM [銅]
RESETCOLOR
PRINTFORM 銅券　
SETCOLOR 0xCCCCCC
PRINTFORM [銀]
RESETCOLOR
PRINTFORM 銀券　
SETCOLOR 0xFFD700
PRINTFORM [金]
RESETCOLOR
PRINTFORM 金券　
SETCOLOR 0xEEAAFF
PRINTFORM [白]
RESETCOLOR
PRINTFORM 白金券　
SETCOLOR 0xFFFF00
PRINTFORM [◆]
RESETCOLOR
PRINTFORML 現在地
RETURN
'''

cell = r'''@SUGOROKU_PRINT_CELL(ARG)
; 各色は凡例の効果と一対一に対応する。現在地は効果表示より優先する。
IF ARG:0 == FLAG:33
	LOCAL:0 = 0xFFFF00
	LOCALS '= @"◆"
ELSEIF ARG:0 == 0
	LOCAL:0 = 0x00FF80
	LOCALS '= @"発"
ELSEIF ARG:0 == 1 || ARG:0 == 2 || ARG:0 == 4 || ARG:0 == 7 || ARG:0 == 19
	LOCAL:0 = 0x88CCFF
	LOCALS '= @"通"
ELSEIF ARG:0 == 3 || ARG:0 == 13
	LOCAL:0 = 0xFFCC00
	LOCALS '= @"★"
ELSEIF ARG:0 == 5 || ARG:0 == 15
	LOCAL:0 = 0x88FF44
	LOCALS '= @"品"
ELSEIF ARG:0 == 6
	LOCAL:0 = 0xCC7722
	LOCALS '= @"銅"
ELSEIF ARG:0 == 8 || ARG:0 == 10 || ARG:0 == 11
	LOCAL:0 = 0xFF8800
	LOCALS '= @"特"
ELSEIF ARG:0 == 9
	LOCAL:0 = 0x44AAFF
	LOCALS '= @"休"
ELSEIF ARG:0 == 12
	LOCAL:0 = 0xCCCCCC
	LOCALS '= @"銀"
ELSEIF ARG:0 == 16
	LOCAL:0 = 0xFFD700
	LOCALS '= @"金"
ELSEIF ARG:0 == 14 || ARG:0 == 17
	LOCAL:0 = 0xFF2200
	LOCALS '= @"緊"
ELSEIF ARG:0 == 18
	LOCAL:0 = 0xEEAAFF
	LOCALS '= @"白"
ELSE
	LOCAL:0 = 0xFFFFFF
	LOCALS '= @"?"
ENDIF
SETCOLOR LOCAL:0
IF ARG:0 < 10
	PRINTFORM [0{ARG:0}:%LOCALS%]
ELSE
	PRINTFORM [{ARG:0}:%LOCALS%]
ENDIF
RESETCOLOR
RETURN

; 盤面画像へ現在地のコマを直接描画する（画像はHTML表示前のグラフィックバッファ）。
@SUGOROKU_DRAW_PAWN(ARG)
SELECTCASE ARG:0
CASE 0
	LOCAL:0 = 55
	LOCAL:1 = 10
CASE 1
	LOCAL:0 = 263
	LOCAL:1 = 10
CASE 2
	LOCAL:0 = 455
	LOCAL:1 = 10
CASE 3
	LOCAL:0 = 643
	LOCAL:1 = 10
CASE 4
	LOCAL:0 = 832
	LOCAL:1 = 10
CASE 5
	LOCAL:0 = 1022
	LOCAL:1 = 10
CASE 6
	LOCAL:0 = 1210
	LOCAL:1 = 10
CASE 7
	LOCAL:0 = 1400
	LOCAL:1 = 10
CASE 8
	LOCAL:0 = 1523
	LOCAL:1 = 10
CASE 9
	LOCAL:0 = 1523
	LOCAL:1 = 380
CASE 10
	LOCAL:0 = 1523
	LOCAL:1 = 695
CASE 11
	LOCAL:0 = 1400
	LOCAL:1 = 695
CASE 12
	LOCAL:0 = 1210
	LOCAL:1 = 695
CASE 13
	LOCAL:0 = 1022
	LOCAL:1 = 695
CASE 14
	LOCAL:0 = 832
	LOCAL:1 = 695
CASE 15
	LOCAL:0 = 643
	LOCAL:1 = 695
CASE 16
	LOCAL:0 = 455
	LOCAL:1 = 695
CASE 17
	LOCAL:0 = 263
	LOCAL:1 = 695
CASE 18
	LOCAL:0 = 55
	LOCAL:1 = 695
CASEELSE
	LOCAL:0 = 55
	LOCAL:1 = 380
ENDSELECT
IF GCREATED(1)
	GDRAWG 0, 1, LOCAL:0, LOCAL:1, 123, 220, 0, 0, 123, 220
ELSE
	; コマ画像が読めない環境では、従来の文字コマを代替表示する。
	GSETFONT 0, "Meiryo UI", 64, 1
	GSETBRUSH 0, 0xFFFFE600
	GDRAWTEXT 0, "●", LOCAL:0, LOCAL:1
ENDIF
RETURN
'''

new_text = text[:draw_start] + draw + '\n' + cell + text[cell_end:]
path.write_bytes(new_text.encode('cp932'))
print('すごろく盤面を整列済みテキストUIへ更新しました。')
